### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 3

### ISSUE THREAD

**Issue by mrkio9** [Loukious/TikTokDeviceGenerator#1]
First, install java x32 & 64
Next, add local into of unidbg.jar in **command** 
when run this code, match = none

![image](https://github.com/Loukious/TikTokDeviceGenerator/assets/101476635/6ae41dbc-3b0b-4452-a81f-befbb707ca14)

![image](https://github.com/Loukious/TikTokDeviceGenerator/assets/101476635/cfa7964a-f2cd-45e7-81cb-aed82ca3ea4c)

i've printed subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True).communicate()
result -> (b'', b'Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 3\r\n\tat com.bytedance.frameworks.core.encrypt.TTEncrypt.main(TTEncrypt.java:66)\r\n')
-> stdout = None , stderr = b'Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 3\r\n\tat com.bytedance.frameworks.core.encrypt.TTEncrypt.main(TTEncrypt.java:66)\r\n'
How to solve?

**Comment by Loukious** [comment]
Try the exe from release.

**Comment by mrkio9** [comment]
i have tested exe from relase first. but it still error because **match** variable = none.

**Comment by Loukious** [comment]
Can you post the output from doing `java -version`?

**Comment by mrkio9** [comment]
![image](https://github.com/Loukious/TikTokDeviceGenerator/assets/101476635/672c647c-d11d-4b18-8cc0-d0ddef97a529)

**Comment by mrkio9** [comment]
I've reinstall java newest version and turn off windows antivirus. and it working. 
maybe, it related to windows antivirus. btw, it's working. now, im going to test it with streamkey.

**Comment by Loukious** [comment]
Amazing.
